spring:
  datasource:
    url: "jdbc:postgresql:foo"
    username: "foo"
    password: "secret"

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: create